name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  tests:
    name: Tests (Py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
      - name: Lint (flake8)
        run: flake8 .
      - name: Run tests
        run: pytest -q tests/

  trivy:
    name: Trivy scan (codebase)
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Trivy FS -> SARIF
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH,MEDIUM

      - name: Upload SARIF to GitHub Security (ignore if disabled)
        uses: github/codeql-action/upload-sarif@v3
        continue-on-error: true
        with:
          sarif_file: trivy-results.sarif

      - name: Upload Trivy report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.sarif
